services:
  web:
    image: php:8.3-apache
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mariadb
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

